#!/usr/bin/env python3
"""
Milvus Batch Processor
Handles bulk operations including indexing, updates, and deletes with batching logic.
"""

import json
from typing import Any

from pymilvus import MilvusClient

from docpipe.core.constants import OperatorConstants
from docpipe.utils.infrastructure.logging import get_logger
from docpipe.utils.operators.vectordb_utils import calculate_batch_size_bytes

logger = get_logger()


# Batch processing constants
DEFAULT_BATCH_SIZE: int = 100
MAX_BATCH_SIZE_MB: int = 3  # Maximum batch size in MB
BULK_INSERT_TIMEOUT: int = 180  # 3 minutes timeout
BULK_DELETE_BATCH_SIZE: int = 500


class MilvusBatchProcessor:
    """
    Manages batch operations for Milvus including bulk indexing and deletes.

    Responsibilities:
    - Size-aware batch processing
    - Bulk indexing with error tracking
    - Bulk delete operations
    - Document preparation and validation
    - Query operations
    """

    def __init__(
        self,
        *,
        client: MilvusClient,
        collection_name: str,
        batch_size: int = DEFAULT_BATCH_SIZE,
        available_features: dict[str, Any] | None = None,
        feature_mappings: dict[str, str] | None = None,
        primary_key_field: str = "pk",
        embeddings_column: str = OperatorConstants.Operators.EMBEDDINGS,
        add_sparse_vector: bool = False,
    ) -> None:
        """
        Initialize the batch processor.

        Args:
            connection_alias: Milvus connection alias
            collection_name: Name of the collection
            batch_size: Maximum documents per batch
            available_features: Feature configuration
            feature_mappings: Column to field mappings
            primary_key_field: Name of primary key field
            embeddings_column: Name of embeddings column
            add_sparse_vector: Whether to use sparse vectors instead of dense vectors
        """
        self.client = client
        self.collection_name = collection_name
        self.batch_size = batch_size
        self.available_features = available_features or {}
        self.feature_mappings = feature_mappings or {}
        self.primary_key_field = primary_key_field
        self.embeddings_column = embeddings_column
        self.add_sparse_vector = add_sparse_vector

    def prepare_document(self, *, row_data: dict[str, Any]) -> dict[str, Any]:  # NOSONAR python:S3776
        """
        Prepare a document for indexing by mapping columns to collection fields.
        Handles both dense and sparse vector modes.

        Only fields explicitly listed in feature_mappings will be included in the
        indexed document. This ensures predictable behavior and matches the
        documented configuration pattern.

        Args:
            row_data: Raw row data from PyArrow table

        Returns:
            Prepared document ready for indexing
        """
        doc: dict[str, Any] = {}

        # Process only fields defined in feature_mappings
        for feature_name, mapped_name in self.feature_mappings.items():
            # Skip sparse_embeddings field - it's auto-generated by BM25 function
            if self.add_sparse_vector and feature_name == OperatorConstants.Columns.SPARSE_EMBEDDINGS_COLUMN_DEFAULT:
                continue

            # Get value from row data
            value = row_data.get(feature_name)

            if value is None:
                continue

            # Get feature config for type information and validation
            feature_config: dict[str, Any] = self.available_features.get(feature_name, {})

            # Skip if explicitly marked as unavailable for vector db
            if feature_config.get(OperatorConstants.Config.AVAILABLE_FOR_VECTOR_DB) is False:
                continue

            # Skip binary data types that cannot be JSON serialized
            if isinstance(value, (bytes, bytearray)):
                continue

            # Convert numpy arrays to lists for JSON serialization
            if hasattr(value, "tolist"):
                value = value.tolist()

            # Parse JSON strings for object/nested types if type is specified
            feature_type: str = feature_config.get("type", "text")
            if feature_type in ("object", "nested", "json") and isinstance(value, str):
                try:
                    value = json.loads(value)
                except (json.JSONDecodeError, TypeError):
                    # If parsing fails, keep as string
                    pass

            doc[mapped_name] = value

        return doc

    def create_batches(self, *, documents: list[tuple[str, dict[str, Any]]]) -> list[list[dict[str, Any]]]:
        """
        Create batches from documents considering both count and size limits.

        Args:
            documents: List of (doc_id, document_dict) tuples

        Returns:
            List of batches, where each batch is a list of prepared documents
        """
        batches: list[list[dict[str, Any]]] = []
        current_batch: list[dict[str, Any]] = []
        current_size: int = 0
        max_size_bytes: int = MAX_BATCH_SIZE_MB * 1024 * 1024

        logger.info(f"Creating batches from {len(documents)} documents (max_batch_size={MAX_BATCH_SIZE_MB}MB)")

        for doc_id, doc_data in documents:
            # Prepare document
            prepared_doc = self.prepare_document(row_data=doc_data)

            logger.info(
                f"Prepared document {doc_id}: fields={list(prepared_doc.keys())}, has_pk={self.primary_key_field in prepared_doc}"
            )

            # Add primary key
            prepared_doc[self.primary_key_field] = doc_id

            # Calculate document size
            doc_size = calculate_batch_size_bytes(documents=[prepared_doc])

            # Check if adding this document would exceed limits
            if current_batch and (len(current_batch) >= self.batch_size or (current_size + doc_size) > max_size_bytes):
                batches.append(current_batch)
                current_batch = []
                current_size = 0

            current_batch.append(prepared_doc)
            current_size += doc_size

        # Add remaining documents
        if current_batch:
            batches.append(current_batch)

        logger.info(
            f"Created {len(batches)} batches from {len(documents)} documents, total docs in batches: {sum(len(b) for b in batches)}"
        )
        return batches

    def process_batches(self, *, batches: list[list[dict[str, Any]]]) -> tuple[int, list[dict[str, Any]]]:
        """
        Process multiple batches of documents.

        Args:
            batches: List of document batches

        Returns:
            Tuple of (success_count, failed_items)
        """
        total_success = 0
        all_failed: list[dict[str, Any]] = []

        logger.info(
            f"Starting batch insertion: {len(batches)} batches, total documents: {sum(len(b) for b in batches)}"
        )

        for i, batch in enumerate(batches):
            try:
                batch_size = len(batch)
                logger.info(
                    f"[MILVUS INSERT] Batch {i + 1}/{len(batches)}: Inserting {batch_size} documents into collection '{self.collection_name}'"
                )

                # Insert batch into Milvus
                result = self.client.insert(collection_name=self.collection_name, data=batch)

                # Milvus insert returns the number of inserted entities
                if isinstance(result, dict):
                    success_count = result.get("insert_count", len(batch))
                    logger.info(
                        f"[MILVUS INSERT] Batch {i + 1}/{len(batches)}: Successfully inserted {success_count} documents (result: {result})"
                    )
                else:
                    success_count = len(batch)
                    logger.info(
                        f"[MILVUS INSERT] Batch {i + 1}/{len(batches)}: Successfully inserted {success_count} documents"
                    )

                total_success += success_count

            except Exception as e:
                logger.error(f"[MILVUS INSERT] Batch {i + 1}/{len(batches)} FAILED: {e}")
                # Add all documents in failed batch to failed items
                for doc in batch:
                    all_failed.append({"document": doc, "error": str(e)})

        logger.info(
            f"[MILVUS INSERT] ✓ Batch insertion complete: {total_success} documents inserted successfully, {len(all_failed)} failed"
        )

        return total_success, all_failed

    def query_by_doc_names(self, *, doc_names: list[str], fields: list[str] | None = None) -> list[dict[str, Any]]:
        """
        Query documents by their names (IDs).

        Args:
            doc_names: List of document names to query
            fields: Optional list of fields to return

        Returns:
            List of matching documents
        """
        try:
            # Build filter expression
            filter_expr = f"{self.primary_key_field} in {doc_names}"

            # Query documents
            results = self.client.query(
                collection_name=self.collection_name,
                filter=filter_expr,
                output_fields=fields or ["*"],
            )

            return results

        except Exception as e:
            logger.error(f"Query by doc names failed: {e}")
            return []

    def delete_documents_by_ids(self, *, doc_ids: list[str]) -> tuple[int, int]:
        """
        Delete documents by their IDs.

        Args:
            doc_ids: List of document IDs to delete

        Returns:
            Tuple of (success_count, failed_count)
        """
        if not doc_ids:
            return 0, 0

        try:
            # Create batches for deletion
            batches = [doc_ids[i : i + BULK_DELETE_BATCH_SIZE] for i in range(0, len(doc_ids), BULK_DELETE_BATCH_SIZE)]

            total_success = 0
            total_failed = 0

            for batch in batches:
                try:
                    # Build filter expression for deletion
                    filter_expr = f"{self.primary_key_field} in {batch}"

                    # Delete documents
                    result = self.client.delete(collection_name=self.collection_name, filter=filter_expr)

                    # Milvus delete returns the number of deleted entities
                    if isinstance(result, dict):
                        delete_count = result.get("delete_count", len(batch))
                    else:
                        delete_count = len(batch)

                    total_success += delete_count

                except Exception as e:
                    logger.error(f"Delete batch failed: {e}")
                    total_failed += len(batch)

            return total_success, total_failed

        except Exception as e:
            logger.error(f"Delete documents failed: {e}")
            return 0, len(doc_ids)

    def get_document_count(self) -> int:
        """
        Get total document count in the collection.

        Returns:
            Number of documents in the collection
        """
        try:
            stats = self.client.get_collection_stats(collection_name=self.collection_name)
            return stats.get("row_count", 0)
        except Exception as e:
            logger.error(f"Failed to get document count: {e}")
            return 0
