/**
 * @file conditionTypes.ts
 *
 * Shared types, constants, and pure utility functions for SQL-filter condition
 * building. Consumed by:
 *
 * - {@link ConditionBuilderTearsheet} — the tabbed tearsheet UI
 * - {@link CriteriaFullViewTearsheet} — the full-screen expand view
 * - {@link AnnotationFilterPanelBody} — the main panel body
 *
 * Keeping these here (rather than in each component file) means any future
 * operator that needs the same condition-builder UI (e.g. a Branching operator)
 * can import directly from this module.
 *
 * @module conditionTypes
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * A single filter condition in the Simple-mode condition builder.
 *
 * Conditions are stored inside {@link CriteriaJson.criteria_list} and are
 * mapped one-to-one with rows in the condition builder UI.
 */
export interface Condition {
  /** Stable unique identifier generated by {@link generateConditionId}. */
  id: string;
  /** Feature/column name selected from the upstream node's `input_features`. */
  variable: string;
  /**
   * SQL comparison operator (e.g. `==`, `>=`, `like`).
   * One of the `value` fields in {@link SQL_OPERATORS}.
   */
  operator: string;
  /** Right-hand side value as a string; empty string for null-check operators. */
  value: string;
}

/**
 * The structured object written to the `criteria_json` Elyra parameter in
 * Simple mode.
 *
 * @example
 * ```json
 * {
 *   "logical_operator": "AND",
 *   "criteria_list": [
 *     { "id": "cond-...", "variable": "lang_score", "operator": ">=", "value": "0.3" }
 *   ]
 * }
 * ```
 */
export interface CriteriaJson {
  /** How multiple conditions are combined — `"AND"` or `"OR"`. */
  logical_operator: string;
  /** Ordered list of individual filter conditions. */
  criteria_list: Condition[];
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * Allowed values for the logical operator that combines multiple conditions.
 * Used by the radio group in the Simple tab and as a default fallback.
 */
export const LOGICAL = { AND: 'AND', OR: 'OR' } as const;

/**
 * All SQL comparison operators available in the condition builder dropdown,
 * ordered from most common to least common.
 *
 * Null-check operators (`is null`, `is not null`) suppress the value input
 * in the condition row UI.
 */
export const SQL_OPERATORS = [
  { label: 'Equals (==)', value: '==' },
  { label: 'Not equals (!=)', value: '!=' },
  { label: 'Greater than (>)', value: '>' },
  { label: 'Less than (<)', value: '<' },
  { label: 'Greater than or equal (>=)', value: '>=' },
  { label: 'Less than or equal (<=)', value: '<=' },
  { label: 'In', value: 'in' },
  { label: 'Not In', value: 'not in' },
  { label: 'Like', value: 'like' },
  { label: 'Not Like', value: 'not like' },
  { label: 'Is Null', value: 'is null' },
  { label: 'Is Not Null', value: 'is not null' },
  { label: 'Between', value: 'between' },
] as const;

/** Union of all valid SQL operator value strings. */
export type SqlOperatorValue = typeof SQL_OPERATORS[number]['value'];

/**
 * Canonical string tags for feature types returned by the backend.
 * Used to branch the value input and operator filter logic.
 */
export const FEATURE_TYPES = {
  BOOLEAN: 'boolean',
  BOOL: 'bool',
  DATETIME: 'datetime',
  JSON: 'json',
  INT32: 'int32',
  INT64: 'int64',
  FLOAT: 'float',
} as const;

/**
 * Feature types that use `NumberInput` for value entry.
 * Covers all fixed-precision numeric types.
 */
export const NUMERIC_TYPES: string[] = [
  FEATURE_TYPES.INT32,
  FEATURE_TYPES.INT64,
  FEATURE_TYPES.FLOAT,
];

/**
 * Datetime input placeholder shown beneath the TextInput for datetime fields.
 */
export const DATETIME_PLACEHOLDER = 'YYYY-MM-DD HH:MM:SS';

/**
 * Regex that validates a datetime string in `YYYY-MM-DD HH:MM:SS` format.
 * Applied to datetime fields on every keystroke to produce inline error messages.
 */
export const TIMESTAMP_REGEX = /^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}$/;

/**
 * Operator strings allowed per feature type.
 *
 * Used in `ConditionBuilderTearsheet` to filter the Operator dropdown to only
 * show operators that make sense for the selected variable's type.
 */
export const OPERATORS_BY_TYPE: Record<string, string[]> = {
  string: ['==', '!=', 'like', 'not like', 'is null', 'is not null', 'in', 'not in', 'between'],
  int32: ['==', '!=', '>', '<', '>=', '<=', 'is null', 'is not null', 'between'],
  int64: ['==', '!=', '>', '<', '>=', '<=', 'is null', 'is not null', 'between'],
  float: ['==', '!=', '>', '<', '>=', '<=', 'is null', 'is not null', 'between'],
  bool: ['==', '!=', 'is null', 'is not null'],
  boolean: ['==', '!=', 'is null', 'is not null'],
  datetime: ['==', '!=', '>', '<', '>=', '<=', 'is null', 'is not null', 'between'],
  json: ['==', '!=', 'is null', 'is not null'],
  vector: ['==', '!=', 'is null', 'is not null'],
  vector_sparse: ['==', '!=', 'is null', 'is not null'],
  default: ['==', '!=', 'is null', 'is not null'],
};

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

/**
 * Generates a collision-resistant ID for a new condition row.
 *
 * Uses `crypto.getRandomValues` for entropy rather than `Math.random` so that
 * IDs remain unique even when many conditions are added in rapid succession.
 *
 * @returns A string of the form `"cond-<timestamp>-<randomHex>"`.
 */
export function generateConditionId(): string {
  const bytes = new Uint8Array(8);
  globalThis.crypto.getRandomValues(bytes);
  const hex = Array.from(bytes).map((b) => b.toString(16).padStart(2, '0')).join('');
  return `cond-${Date.now()}-${hex}`;
}

/**
 * Converts a structured {@link Condition} into a human-readable display string.
 *
 * Used when rendering rows in the criteria table and the full-view tearsheet.
 *
 * @param condition - The condition to format.
 * @returns A string of the form `"<variable> <operator> <value>"`.
 *
 * @example
 * ```ts
 * conditionToText({ id: '…', variable: 'lang_score', operator: '>=', value: '0.3' })
 * // → "lang_score >= 0.3"
 * ```
 */
export function conditionToText(condition: Condition): string {
  return `${condition.variable} ${condition.operator} ${condition.value}`;
}

/**
 * Returns `true` when `value` is a valid JSON string.
 * Used to validate condition values for `json`-typed features.
 *
 * @param value - The string to test.
 */
export function isValidJSON(value: string): boolean {
  try {
    JSON.parse(value);
    return true;
  } catch {
    return false;
  }
}
