repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # until Mend supports `uv` directly, an export to requirements.txt is needed.
    # the .whitesource.config is adjusted accordingly
    # uv version.
    rev: 0.6.5
    hooks:
      - id: uv-export
        files: ^(pyproject\.toml|uv\.lock)$
        args:
          [
            "--no-hashes",
            "--frozen",
            "--output-file=requirements.txt",
            "--no-dev",
            "--all-packages",
          ]

  # Python linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      - id: ruff-format
        files: ^.*\.py$
      - id: ruff
        args: [--fix]
        files: ^.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --config-file=pyproject.toml]
        additional_dependencies: [types-requests, types-cachetools]
        files: ^src/datasift/.*\.py$

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: ^(package\.lock\.json|.*venv/.*|.*\.venv/.*|.*env/.*|.*\.env/.*)$
