sonar.host.url=https://sonarqube-prod.apps.wdc-sonarqube-prod.core.cirrus.ibm.com
sonar.language=py
sonar.python.version=3.12
sonar.sources=src/datasift_opensource
sonar.verbose=true
sonar.exclusions=**/ui/**,**/__pycache__/**,**/*.pyc
sonar.tests=tests
sonar.links.scm=https://github.ibm.com/wdp-gov/datasift-opensource
sonar.links.homepage=https://github.ibm.com/wdp-gov/datasift-opensource
sonar.links.issue=https://github.ibm.com/wdp-gov/tracker
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
sonar.projectName=datasift-opensource
sonar.projectKey=56865-datasift-opensource
