[app_config]
name = "DatasiftApp"
iam_public_key_url = "https://cpd-wkc.apps.udptest7.cp.fyre.ibm.com/auth/jwtpublic"
cp4d_base_url = "https://cpd-wkc.apps.udptest7.cp.fyre.ibm.com"
wml_url = "https://cpd-wkc.apps.udptest7.cp.fyre.ibm.com"
wml_server = "https://cpd-wkc.apps.udptest7.cp.fyre.ibm.com"
data_folder = "/tmp/data"
warehouse_folder = "/tmp"
log_level = "INFO"
local_mode = true
operand_namespace="wkc"
tls_path="abc"
audit_logging = "FALSE"
at_tracker = "FALSE"
datasift_postgres_host = "pgres1.fyre.ibm.com"
datasift_postgres_port = 5432
datasift_postgres_database = "datasift"
datasift_postgres_user = "postgres"
datasift_postgres_password = "pgsql123"    #pragma: allowlist secret

# CP4D tests related configurations
test_cp4d_base_url = "https://cpd-wkc.apps.udptest7.cp.fyre.ibm.com"
test_cp4d_project_id = "87ee7779-d92f-49a8-807a-45d04735bb63"
test_cp4d_asset_ids = ["434a9231-0778-4e8d-b652-a0edd77cb8c2"]
test_cp4d_flow_id = "42b9837a-bf5c-47b0-8158-867a7d5447e5"
test_cp4d_s3_connection_id = "563aa142-fb0f-41f7-a247-b7466f7b0c75"
test_cp4d_milvus_connection_id = "5594ca58-593e-483a-b1c3-aaf00bb67be9"
test_cp4d_es_connection_id = "98f83fc3-b403-4fbd-9ec5-53440282ee6a"
test_cp4d_presto_connection_id = "189c397f-0d38-4149-a047-605dc59f94a1" # not updated, please update and remove comment
test_cp4d_document_library_id = "8274e260-9405-492f-b322-dbb9deb312f3"  # not updated, please update and remove comment
test_cp4d_catalog_id = "d0425494-aec1-400e-9f74-1eddaa1afcfa"   # not updated, please update and remove comment
