import argparse
import gc
import json
import os
import threading
import tracemalloc

from common.constants.constants import DatasiftConstants, OrchestratorType
from common.exceptions.datasift_exceptions import FlowValidationException, ValidationAlertEncoder
from common.models.session_info import get_session_info
from common.util.log import get_logger
from core.orchestrator.abstract_orchestrator import AbstractOrchestrator
from core.orchestrator.flow_validator import FlowValidator
from core.orchestrator.orchestrator_factory import OrchestratorFactory

logger = get_logger()
lock = threading.Lock()


class FlowExecutor:
    """
    This class is responsible for loading a flow definition from a JSON file, instantiating
    an orchestrator object, executing the flow, and visualizing the flow.
    ## Attributes
    - flow_def: A dictionary containing the flow definition loaded from the JSON file.
    """

    def __init__(self, flow_def_file: str = None, flow_def: dict = None, orchestrator=None):
        """
        Loads the flow definition from the given JSON file and stores it in the `flow_def` attribute.
        Parameters:
        - flow_def_file: The path to the JSON file containing the flow definition.
        - flow_def: Actual flow definition in JSON format. Will be ignored if flow_def_file is passed
        - orchestrator: Orchestrator to be used by this flow executor.
        """
        self.session_info = get_session_info()
        self.common_log_arguments = self.session_info.get_common_log_arguments()
        self.__orchestrator = orchestrator
        if flow_def_file is not None:
            with open(flow_def_file) as json_file:
                self.flow_def = json.load(json_file).get("flow")
        else:
            self.flow_def = flow_def
        self.trace_memory_allocations = os.getenv(DatasiftConstants.TRACE_MEMORY_ALLOCATIONS, False)

    def __str__(self):
        """ "
        Returns a string representation of the flow object.
        Returns:
        - A string representation of the flow object in the format `[Name: <name>, Description: <description>]`
        """
        return f"[ Name: {self.flow_def.get('name')}, Description: {self.flow_def.get('description')} ]"

    def execute(self, *, orchestrator: AbstractOrchestrator, params: dict | None = None):
        """
        Executes the flow using the given orchestrator returns the DataAccess generated by the flow
        Parameters:
        - orchestrator: An instance of an orchestrator that will be used to execute the flow.
        - params: A dictionary of runtime parameters
        """
        FlowExecutor.start_diagnostic_collection(self)
        if orchestrator is not None:
            self.__orchestrator = orchestrator

        try:
            if self.__orchestrator.job_tracker.cancel_job_run_if_cancelling(
                    job_run_id=self.session_info.job_run_id,
                    job_log_path=self.__orchestrator.job_log_path):
                logger.info(
                    ">>> Cancelled the execution: %s",
                    params[DatasiftConstants.JOB_RUN_ID],
                )
                return
            flow_validator = FlowValidator(self.__orchestrator)
            flow_validator.validate(flow_def=self.flow_def, params=params)
        except FlowValidationException as exc:
            if len(exc.errors) == 0:
                # if there are no errors (only warnings), go ahead with the flow execution
                logger.warning(
                    f"Flow definition has warnings: {json.dumps(exc.warnings, cls=ValidationAlertEncoder)}",
                    extra=self.common_log_arguments,
                )
            else:
                raise exc

        FlowExecutor.print_diagnostic_info(self)
        try:
            data_access = self.__orchestrator.execute(flow_def=self.flow_def, params=params)
        except Exception as exc:
            logger.error(exc)
            raise exc
        with lock:
            gc.collect()
            FlowExecutor.print_diagnostic_info(self)
            FlowExecutor.stop_diagnostic_collection(self)
        return data_access

    def cancel(self):
        if self.__orchestrator is not None:
            self.__orchestrator.cancel()

    def pause(self):
        if self.__orchestrator is not None:
            self.__orchestrator.pause()

    def resume(self):
        if self.__orchestrator is not None:
            self.__orchestrator.resume()

    def start_diagnostic_collection(self):
        if self.trace_memory_allocations:
            logger.info(
                ">>> Starting to collect memory allocation traces",
                extra=self.common_log_arguments,
            )
            tracemalloc.start()

    def stop_diagnostic_collection(self):
        if self.trace_memory_allocations:
            logger.info(
                ">>> Stopping to collect memory allocation traces",
                extra=self.common_log_arguments,
            )
            tracemalloc.stop()

    def print_diagnostic_info(self, *, key_type="lineno", limit=10, snapshot=None):
        """
        Print the memory usage information including top n memory consumers
        """
        import linecache
        import os

        gc_stats = gc.get_stats()
        logger.info(f"GC stats: {gc_stats}", extra=self.common_log_arguments)

        if self.trace_memory_allocations:
            if snapshot is None:
                snapshot = tracemalloc.take_snapshot()

            top_stats = snapshot.statistics(key_type)

            logger.info("-" * 80, extra=self.common_log_arguments)
            logger.info("| Top %s lines" % limit, extra=self.common_log_arguments)
            logger.info("=" * 80, extra=self.common_log_arguments)
            for index, stat in enumerate(top_stats[:limit], 1):
                frame = stat.traceback[0]
                # replace "/path/to/module/file.py" with "module/file.py"
                filename = os.sep.join(frame.filename.split(os.sep)[-2:])
                logger.info(
                    "| #%s: %s:%s: %.1f KiB" % (index, filename, frame.lineno, stat.size / 1024),
                    extra=self.common_log_arguments,
                )
                line = linecache.getline(frame.filename, frame.lineno).strip()
                if line:
                    logger.info("|     %s" % line, extra=self.common_log_arguments)

            other = top_stats[limit:]
            if other:
                size = sum(stat.size for stat in other)
                logger.info(
                    "| %s other: %.1f KiB" % (len(other), size / 1024),
                    extra=self.common_log_arguments,
                )
            total = sum(stat.size for stat in top_stats)
            logger.info(
                "| Total allocated size: %.1f KiB" % (total / 1024),
                extra=self.common_log_arguments,
            )
            logger.info("=" * 80, extra=self.common_log_arguments)


# main entry point into the program
def main():  # pragma: no cover
    parser = argparse.ArgumentParser(description="Run flow json file")
    parser.add_argument(
        "-f",
        "--file",
        help="input filename to be executed (default: tests/flow_local.json)",
        default="tests/flow_local.json",
    )
    parser.add_argument(
        "-o",
        "--orchestrator",
        help="Orchestrator to be used (default: python)",
        default=OrchestratorType.PYTHON,
    )
    args = parser.parse_args()

    logger.info(f"Running flow [{args.file}] with orchestrator [{args.orchestrator}]")

    flow = FlowExecutor(flow_def_file=args.file)
    logger.info(f">>> Loaded flow {flow!s}")
    logger.debug(flow.flow_def)

    orchestrator = OrchestratorFactory.create_orchestrator()
    try:
        flow.execute(
            orchestrator=orchestrator,
            params={
                DatasiftConstants.JOB_ID: "5df177f6-92bc-4465-826e-f4df207ffb71",
                DatasiftConstants.JOB_RUN_ID: "5df177f6-92bc-4465-826e-f4df207ffb75",
            },
        )
        logger.info(f"Successfully completed flow execution in background thread. orchestrator: {orchestrator}")
    except Exception as exc:
        logger.error(f"Flow execution failed in background thread. message: {exc!s},\n orchestrator: {orchestrator}")
        logger.error(exc, stack_info=True, exc_info=True)


# main entry point into the program; used for launching the flow executor
if __name__ == "__main__":  # pragma: no cover
    main()
