import json
import os

import numpy as np
import pyarrow as pa

from docpipe.core.constants import DocpipeConstants
from docpipe.exceptions.docpipe_exceptions import DocpipeException
from docpipe.utils.infrastructure.logging import get_logger

logger = get_logger()


def write_content_to_file(content_list, filepath):
    """
    Write embeddings to a memmap file and optionally save dimension metadata.

    Parameters
    ----------
    content_list : list
        List of embeddings to write
    filepath : str
        Path to the memmap file
    """
    # Create directory structure if it doesn't exist
    directory = os.path.dirname(filepath)
    if directory and not os.path.exists(directory):
        os.makedirs(directory, exist_ok=True)
        logger.info(f"Created directory: {directory}")

    with open(filepath, "ab") as f:
        for content in content_list:
            arr = np.asarray(content, dtype=np.float32)
            arr.tofile(f)

    # Save dimension metadata if provided and this is the first write
    if content_list and len(content_list) > 0:
        dim = len(content_list[0])
        metadata_path = filepath + DocpipeConstants.METADATA_SUFFIX
        if not os.path.exists(metadata_path):
            write_embedding_metadata(filepath, dim)


def write_embedding_metadata(filepath, dim):
    """
    Write embedding dimension metadata to a companion file.

    Parameters
    ----------
    filepath : str
        Path to the memmap file
    dim : int
        Dimension of the embeddings
    """
    metadata_path = filepath + DocpipeConstants.METADATA_SUFFIX
    metadata = {"dim": dim}

    with open(metadata_path, "w") as f:
        json.dump(metadata, f)

    logger.debug(f"Wrote embedding metadata: dim={dim} to {metadata_path}")


def read_embedding_metadata(filepath):
    """
    Read embedding dimension from metadata file.

    Parameters
    ----------
    filepath : str
        Path to the memmap file

    Returns
    -------
    int
        Dimension of the embeddings

    Raises
    ------
    FileNotFoundError
        If metadata file doesn't exist
    ValueError
        If metadata is invalid
    """
    metadata_path = filepath + DocpipeConstants.METADATA_SUFFIX

    if not os.path.exists(metadata_path):
        raise FileNotFoundError(f"Metadata file not found: {metadata_path}")

    with open(metadata_path) as f:
        metadata = json.load(f)

    if "dim" not in metadata:
        raise DocpipeException(f"Invalid metadata file: missing 'dim' field in {metadata_path}")

    return metadata["dim"]


def yield_embeddings_from_memmap_file(filepath, dim):
    """
    Generator that yields one embedding at a time from a memory-mapped file.

    Parameters:
        filepath : str
            Path to the file from which data
        dim : int
            Dimension of each embedding. It is the number of vectors generated by the embedding model
            for each text e.g 384, 1024 etc
    Yields:
        np.ndarray: One item of shape (dim,)
    """
    # Compute number of embeddings from file size
    file_size = os.path.getsize(filepath)
    embeddings_size = file_size // (dim * 4)
    mmap_array = np.memmap(filepath, dtype=np.float32, mode="r", shape=(embeddings_size, dim))
    try:
        # Yield one embedding at a time
        yield from mmap_array
    finally:
        # Explicitly delete the memmap array to free memory
        del mmap_array


def load_embeddings_from_memmap_file(filepath):
    """
    Load all embeddings from a memory-mapped file into memory.

    Parameters
    ----------
    filepath : str
        Path to the memmap file

    Returns
    -------
    list
        List of embeddings as lists (not numpy arrays)

    Raises
    ------
    FileNotFoundError
        If the file or metadata file doesn't exist
    DocpipeException
        If metadata is invalid
    """
    # Read dimension from metadata file
    dim = read_embedding_metadata(filepath)

    # Compute number of embeddings from file size
    file_size = os.path.getsize(filepath)
    embeddings_size = file_size // (dim * 4)

    # Load the embeddings memory mapped file
    mmap_array = np.memmap(filepath, dtype=np.float32, mode="r", shape=(embeddings_size, dim))

    try:
        # Convert to list of lists for JSON serialization
        embeddings_list = [embedding.tolist() for embedding in mmap_array]
        return embeddings_list
    finally:
        # Explicitly delete the memmap array to free memory
        del mmap_array


def write_chunks_to_file(chunks_list, filepath):
    """
    Write chunks to a binary file in streaming fashion.
    Each chunk is written as: [length (4 bytes)] [JSON bytes (UTF-8)]

    Parameters
    ----------
    chunks_list : list
        List of chunks (can be strings or dicts with 'chunk', 'start_index', 'summary' keys)
    filepath : str
        Output binary file path
    """
    # Create directory structure if it doesn't exist
    directory = os.path.dirname(filepath)
    if directory and not os.path.exists(directory):
        os.makedirs(directory, exist_ok=True)
        logger.info(f"Created directory: {directory}")

    with open(filepath, "wb") as f:
        for chunk in chunks_list:
            # Convert chunk to JSON string (handles both strings and dicts)
            if isinstance(chunk, dict):
                chunk_str = json.dumps(chunk)
            else:
                chunk_str = str(chunk)

            # Encode as UTF-8 bytes
            chunk_bytes = chunk_str.encode("utf-8")

            # Write length as 4-byte integer (uint32)
            length = len(chunk_bytes)
            f.write(length.to_bytes(4, byteorder="little"))

            # Write the actual chunk bytes
            f.write(chunk_bytes)

    logger.debug(f"Wrote {len(chunks_list)} chunks to {filepath}")


def yield_chunks_from_file(filepath):
    """
    Generator that yields one chunk at a time from a binary file.

    Parameters
    ----------
    filepath : str
        Path to the binary chunks file

    Yields
    ------
    str
        One chunk at a time (as JSON string if it was a dict, or plain string)
    """
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Chunks file not found: {filepath}")

    with open(filepath, "rb") as f:
        while True:
            # Read length (4 bytes)
            length_bytes = f.read(4)
            if not length_bytes:
                break  # End of file

            length = int.from_bytes(length_bytes, byteorder="little")

            # Read chunk bytes
            chunk_bytes = f.read(length)

            # Decode to string
            chunk = chunk_bytes.decode("utf-8")

            yield chunk


def load_chunks_from_file(filepath):
    """
    Load all chunks from a binary file into memory.

    Parameters
    ----------
    filepath : str
        Path to the binary chunks file

    Returns
    -------
    list
        List of chunks (as parsed JSON dicts or strings)

    Raises
    ------
    FileNotFoundError
        If the file doesn't exist
    """
    chunks_list = []
    for chunk_str in yield_chunks_from_file(filepath):
        try:
            # Try to parse as JSON (for dict chunks)
            chunk = json.loads(chunk_str)
        except Exception as e:
            raise DocpipeException(f"An error occurred when loading chunked content: {e}") from e
        chunks_list.append(chunk)

    return chunks_list


def _load_chunk_data_from_row(chunks_data):
    """Load chunk data from a single row, handling memmap paths."""
    if not isinstance(chunks_data, dict) or DocpipeConstants.CHUNKS_MEMMAP_FILE not in chunks_data:
        return chunks_data

    file_path = chunks_data[DocpipeConstants.CHUNKS_MEMMAP_FILE]
    try:
        logger.debug(f"Loading chunks from memmap file: {file_path}")
        chunks_list = load_chunks_from_file(file_path)
        logger.debug(f"Replaced memmap path with {len(chunks_list)} chunks")
        return chunks_list
    except Exception as e:
        logger.error(f"Failed to load chunks from {file_path}: {e}", exc_info=True)
        raise DocpipeException(f"Cannot load chunks from memmap file {file_path}: {e}") from e


def _check_column_needs_replacement(table: pa.Table, column_name: str, memmap_key: str) -> bool:
    """Check if a column exists and contains memmap file paths."""
    if column_name not in table.column_names:
        return False

    col = table.column(column_name)
    if len(col) == 0:
        return False

    data = col[0].as_py()
    return isinstance(data, dict) and memmap_key in data


def _load_embeddings_data_from_row(embeddings_data):
    """Load embeddings data from a single row, handling memmap paths."""
    if not isinstance(embeddings_data, dict) or DocpipeConstants.EMBEDDINGS_MEMMAP_FILE not in embeddings_data:
        return embeddings_data

    file_path = embeddings_data[DocpipeConstants.EMBEDDINGS_MEMMAP_FILE]
    try:
        logger.debug(f"Loading embeddings from memmap file: {file_path}")
        embeddings_list = load_embeddings_from_memmap_file(file_path)
        logger.debug(f"Replaced memmap path with {len(embeddings_list)} embeddings")
        return embeddings_list
    except Exception as e:
        logger.error(f"Failed to load embeddings from {file_path}: {e}", exc_info=True)
        raise DocpipeException(f"Cannot load embeddings from memmap file {file_path}: {e}") from e


def _process_embeddings_column(table: pa.Table, embeddings_column: str):
    """Process embeddings column and return new array if replacement needed."""
    embeddings_col = table.column(embeddings_column)
    new_embeddings_data = [
        _load_embeddings_data_from_row(embeddings_col[i].as_py()) for i in range(len(embeddings_col))
    ]
    return pa.array(new_embeddings_data)


def _process_chunks_column(table: pa.Table, chunks_column: str):
    """Process chunks column and return new array if replacement needed."""
    chunks_col = table.column(chunks_column)
    new_chunks_data = [_load_chunk_data_from_row(chunks_col[i].as_py()) for i in range(len(chunks_col))]
    return pa.array(new_chunks_data)


def _build_table_with_replaced_columns(
    table: pa.Table, embeddings_column: str, chunks_column: str, new_embeddings_array, new_chunks_array
) -> pa.Table:
    """Build new table with replaced columns, preserving column order."""
    column_arrays = []
    for name in table.column_names:
        if name == embeddings_column and new_embeddings_array is not None:
            column_arrays.append(new_embeddings_array)
        elif name == chunks_column and new_chunks_array is not None:
            column_arrays.append(new_chunks_array)
        else:
            column_arrays.append(table.column(name))

    return pa.table(column_arrays, names=table.column_names)


def replace_memmap_paths_combined(
    table: pa.Table, embeddings_column: str = "embeddings", chunks_column: str = "chunked_content"
) -> pa.Table:
    """
    Replace memmap file paths for both embeddings and chunks in a single pass.

    This optimized function processes both columns together to avoid creating
    multiple temporary tables, reducing memory usage.

    Parameters
    ----------
    table : pa.Table
        PyArrow table with embeddings and/or chunks columns containing memmap file paths
    embeddings_column : str, optional
        Name of the embeddings column (default: "embeddings")
    chunks_column : str, optional
        Name of the chunks column (default: "chunked_content")

    Returns
    -------
    pa.Table
        PyArrow table with both columns containing actual data instead of memmap paths
    """
    # Check if columns need processing
    needs_embeddings = _check_column_needs_replacement(
        table, embeddings_column, DocpipeConstants.EMBEDDINGS_MEMMAP_FILE
    )
    needs_chunks = _check_column_needs_replacement(table, chunks_column, DocpipeConstants.CHUNKS_MEMMAP_FILE)

    if not needs_embeddings and not needs_chunks:
        logger.debug("No memmap file paths found in embeddings or chunks columns")
        return table

    logger.info(f"Replacing memmap paths - embeddings: {needs_embeddings}, chunks: {needs_chunks}")

    # Process columns that need replacement
    new_embeddings_array = _process_embeddings_column(table, embeddings_column) if needs_embeddings else None
    new_chunks_array = _process_chunks_column(table, chunks_column) if needs_chunks else None

    return _build_table_with_replaced_columns(
        table, embeddings_column, chunks_column, new_embeddings_array, new_chunks_array
    )


def cleanup_memmap_files(*, job_id: str, job_run_id: str) -> None:
    """
    Clean up temporary memmap files for a completed job run.
    Removes the chunks_files and embeddings_files directories for the specified job_run_id.
    Parameters
    ----------
    job_id : str
        The job ID
    job_run_id : str
        The job run ID
    """
    import shutil

    from docpipe.utils.infrastructure.filesystem import get_data_path

    try:
        # Clean up chunks_files
        chunks_dir = get_data_path(sub_dir=f"/chunks_files/{job_id}/{job_run_id}")
        if os.path.exists(chunks_dir):
            shutil.rmtree(chunks_dir, ignore_errors=True)
            logger.info(f"Cleaned up chunks directory: {chunks_dir}")

        # Clean up embeddings_files
        embeddings_dir = get_data_path(sub_dir=f"/embeddings_files/{job_id}/{job_run_id}")
        if os.path.exists(embeddings_dir):
            shutil.rmtree(embeddings_dir, ignore_errors=True)
            logger.info(f"Cleaned up embeddings directory: {embeddings_dir}")

    except Exception as e:
        logger.warning(f"Failed to cleanup memmap files for job_run_id {job_run_id}: {e}")
